### ISSUE TITLE
Crate does not build because Cargo.lock is out of date / inconsistent

### ISSUE THREAD

**Issue by ophilli** [broken-motorwerks/bmw_telemetry#1]
bmw_telemetry does not currently build due to semver resolution failure with `embassy-executor`, and `embassy-time` now that https://github.com/embassy-rs/embassy/commit/9a238e6ad8aedf29b5f5af7308c7f5f50061242c has been merged which revved the versions of `embassy-executor` and `embassy-time` (notably the `embassy-executor` crate no longer provides the `integrated-timers` feature used by bmw_telemetry).

There are also issues because the `Cargo.lock` specifies exactly serde `v1.0.210` but `telemetry-types` specifies serde `v1.0.214` or newer.

This could be fixed by committing and merging the Cargo.lock that @christianheussy is likely building / testing with locally, or by updating the `Cargo.toml` to take the embassy updates like:
```diff --git a/Cargo.toml b/Cargo.toml
index c260f44..0016298 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -5,12 +5,11 @@ edition = "2021"
 
 [dependencies]
 embassy-sync = { version = "0.6.0", features = ["defmt"] }
-embassy-executor = { version = "0.6.0", features = [
+embassy-executor = { version = "0.7.0", features = [
     "arch-cortex-m",
     "executor-thread",
     "executor-interrupt",
     "defmt",
-    "integrated-timers",
 ], git = "https://github.com/embassy-rs/embassy.git" }
 embassy-stm32 = { version = "0.1.0", features = [
     "defmt",
@@ -21,7 +20,7 @@ embassy-stm32 = { version = "0.1.0", features = [
     "exti",
 ], git = "https://github.com/embassy-rs/embassy.git" }
 defmt = "0.3.8"
-embassy-time = { version = "0.3.2", features = [
+embassy-time = { version = "0.4.0", features = [
     "defmt",
     "defmt-timestamp-uptime",
     "tick-hz-32_768",
```
and then running `cargo update` to commit the changes to the lock file & fix the serde issue.

There are no tests in the crate & I'm unfamiliar with the code base so it is not clear what the second order effects of the `embassy-executor` crate's removal of the `integrated-timers` feature may be.

**Comment by christianheussy** [comment]
Attempted to build with:
- embassy-executor = "0.7.0"
- embassy-time = "0.4.0"

However this leads to issues:
```
error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/heussy/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5cbd520/embassy-executor/src/spawner.rs:73:6
   |
73 | impl core::error::Error for SpawnError {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

error[E0599]: no method named `vtable` found for reference `&Waker` in the current scope
  --> /home/heussy/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5cbd520/embassy-executor/src/raw/waker.rs:37:14
   |
37 |     if waker.vtable() as *const _ != &VTABLE as *const _ {
   |              ^^^^^^ method not found in `&Waker`

error[E0599]: no method named `data` found for reference `&Waker` in the current scope
  --> /home/heussy/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5cbd520/embassy-executor/src/raw/waker.rs:41:38
   |
41 |     unsafe { TaskRef::from_ptr(waker.data() as *const TaskHeader) }
   |                                      ^^^^ method not found in `&Waker`
```

Ideally, embassy would push a [new release](https://github.com/embassy-rs/embassy/issues/3560) as the latest on crates.io does not have the CAN implementation required by this repo.

**Comment by christianheussy** [comment]
Created issue [https://github.com/broken-motorwerks/bmw_telemetry/issues/3](https://github.com/broken-motorwerks/bmw_telemetry/issues/3) to track pinning specific embassy commits in the manifest.

**Comment by ophilli** [comment]
Confirmed this is fixed via https://github.com/ophilli/bmw_telemetry/actions/runs/12500808465/job/34877445121
